export const FIND_ALL_SHOWS_BY_GENRE_IN_AND_START_TIME = "FIND_ALL_BY_GENRE_IN_AND_START_TIME";
export const SELECT_SHOW = "SELECT_SHOW";
export const FIND_ALL_SHOWS_BY_GENRE_IN = "FIND_ALL_SHOWS_BY_GENRE_IN";
export const FIND_ALL_PLAYING_NOW_IN_REGION = "FIND_ALL_PLAYING_NOW_IN_REGION";
export const FIND_ALL_WILL_PLAY_IN_REGION = "FIND_ALL_WILL_PLAY_IN_REGION";

export const CHOOSE_PLAYING_NOW = "CHOOSE_PLAYING_NOW";
export const CHOOSE_WILL_PLAY = "CHOOSE_WILL_PLAY";