export const FIND_ALL_SHOWS_BY_GENRE_IN_AND_START_TIME = "FIND_ALL_BY_GENRE_IN_AND_START_TIME";
export const SELECT_SHOW = "SELECT_SHOW";
export const FIND_ALL_SHOWS_BY_GENRE_IN = "FIND_ALL_SHOWS_BY_GENRE_IN";
export const FIND_ALL_BY_PLAYING_NOW = "FIND_ALL_BY_PLAYING_NOW";
export const FIND_ALL_BY_WILL_PLAY = "FIND_ALL_BY_WILL_PLAY";